MODEL_PATH = "weights/best.pt"

CAMERA_INDEX = 0
IMAGE_SIZE = 640
CONFIDENCE = 0.35

ROWS = 4
COLS = 3
TOP_ROW_SIZE_RATIO = 0.90
GRID_MEMORY_MIN_HOLES = 8
GRID_MEMORY_PARTIAL_MAX_HOLES = 5
GRID_MEMORY_MAX_DISTANCE_RATIO = 0.85
GRID_MEMORY_SMOOTHING = 0.25
GRID_GEOMETRY_MAX_ERROR_RATIO = 0.75
GRID_GEOMETRY_ANCHOR_WEIGHT = 0.35
GRID_TRACKER_MIN_MATCHES = 3
GRID_TRACKER_MAX_ERROR_RATIO = 0.65

RED_SCORE_THRESHOLD = 0.05
RED_TARGET_SWITCH_MARGIN = 0.03
TARGET_STABLE_FRAMES = 3
RING_SCALE = 1.25
INNER_SCALE = 0.90

GENERAL_TARGET_CONFIDENCE = 0.50
GENERAL_TARGET_STABLE_FRAMES = 3
TARGET_EDGE_MARGIN_RATIO = 0.015
MAX_SHOTS_PER_HOLE = 3
RED_TARGET_IDS = (1, 2, 3)

SERIAL_BAUD = 115200
SERIAL_HEARTBEAT_SECONDS = 0.10
