MODEL_PATH = "weights/best.pt"

# Camera input. Use "realsense" for the Solomon SLM SVRBP-0092C and
# "opencv" when testing with a normal webcam.
CAMERA_SOURCE = "realsense"
CAMERA_INDEX = 0
IMAGE_SIZE = 640
CONFIDENCE = 0.35

ROWS = 4
COLS = 3
TOP_ROW_SIZE_RATIO = 0.90
GRID_MEMORY_MIN_HOLES = 8
GRID_MEMORY_PARTIAL_MAX_HOLES = 5
GRID_MEMORY_MAX_DISTANCE_RATIO = 0.85
GRID_MEMORY_SMOOTHING = 0.25
GRID_GEOMETRY_MAX_ERROR_RATIO = 0.75
GRID_GEOMETRY_ANCHOR_WEIGHT = 0.35
GRID_TRACKER_MIN_MATCHES = 3
GRID_TRACKER_MAX_ERROR_RATIO = 0.65

RED_SCORE_THRESHOLD = 0.05
RED_TARGET_SWITCH_MARGIN = 0.03
TARGET_STABLE_FRAMES = 3
RING_SCALE = 1.25
INNER_SCALE = 0.90

GENERAL_TARGET_CONFIDENCE = 0.50
GENERAL_TARGET_STABLE_FRAMES = 3
TARGET_EDGE_MARGIN_RATIO = 0.015
MAX_SHOTS_PER_HOLE = 3
RED_TARGET_IDS = (1, 2, 3)

SERIAL_BAUD = 115200
SERIAL_HEARTBEAT_SECONDS = 0.10

# RGB-D distance estimation. All depth and serial distance values are mm.
# The ring samples the board around a detected hole instead of the empty
# center of the hole, which is normally more stable for this target.
DEPTH_MIN_MM = 200
DEPTH_MAX_MM = 8000
DEPTH_RING_INNER_RATIO = 0.60
DEPTH_RING_OUTER_RATIO = 1.10
DEPTH_MIN_VALID_SAMPLES = 40
DEPTH_MIN_VALID_FRACTION = 0.20
DEPTH_MAD_SCALE = 3.5
DEPTH_SMOOTHING = 0.25

# "range" sends the straight-line camera-to-target distance.
# "z" sends only the forward distance along the optical axis.
DEPTH_DISTANCE_MODE = "range"
DEPTH_DISPLAY_MAX_MM = 3000

# Solomon SLM SVRBP-0092C is an Intel RealSense active-stereo camera.
REALSENSE_WIDTH = 1280
REALSENSE_HEIGHT = 720
REALSENSE_FPS = 30
REALSENSE_SERIAL = None
REALSENSE_TIMEOUT_MS = 5000
REALSENSE_WARMUP_FRAMES = 15
REALSENSE_ENABLE_EMITTER = True
